# AMF - Access and Mobility Management Function
logger:
  file:
    path: /var/log/open5gs/amf.log
  level: debug

amf:
  sbi:
    server:
      - address: 172.22.0.12
        port: 7777
    client:
      nrf:
        - uri: http://172.22.0.10:7777
      scp:
        - uri: http://172.22.0.11:7777
  
  ngap:
    server:
      - address: 172.22.0.12
        port: 38412
  
  metrics:
    server:
      - address: 172.22.0.12
        port: 9090
  
  guami:
    - plmn_id:
        mcc: 001
        mnc: 01
      amf_id:
        region: 2
        set: 1
  
  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 1
  
  plmn_support:
    - plmn_id:
        mcc: 001
        mnc: 01
      s_nssai:
        - sst: 1
  
  security:
    integrity_order: [NIA2, NIA1, NIA0]
    ciphering_order: [NEA0, NEA1, NEA2]
  
  network_name:
    full: VulnDB-5G
    short: V5G
  
  amf_name: AMF-VulnDB
  
  time:
    t3502:
      value: 720
    t3512:
      value: 3600