# BSF - Binding Support Function
logger:
  file:
    path: /var/log/open5gs/bsf.log
  level: debug

bsf:
  sbi:
    server:
      - address: 172.22.0.19
        port: 7777
    client:
      nrf:
        - uri: http://172.22.0.10:7777
      scp:
        - uri: http://172.22.0.11:7777

db_uri: mongodb://admin:changeme@172.22.0.50/open5gs?authSource=admin