# SCP - Service Communication Proxy
logger:
  file:
    path: /var/log/open5gs/scp.log
  level: info

scp:
  sbi:
    server:
      - address: 172.22.0.11
        port: 7777
    client:
      nrf:
        - uri: http://172.22.0.10:7777