logger:
  level: info

global:
  max:
    ue: 1024

smf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
      advertise: 172.22.0.13
    client:
      scp:
        - uri: http://172.22.0.11:7777
      nrf:
        - uri: http://172.22.0.10:7777

  pfcp:
    server:
      - address: 172.22.0.13
    client:
      upf:
        - address: 172.22.0.20

  gtpc:
    server:
      - address: 172.22.0.13

  gtpu:
    server:
      - address: 172.22.0.13

  metrics:
    server:
      - address: 172.22.0.13
        port: 9090

  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet
    - subnet: 10.46.0.0/16
      gateway: 10.46.0.1
      dnn: ims

  dns:
    - 8.8.8.8
    - 8.8.4.4

  mtu: 1400

  ctf:
    enabled: auto

upf:
  pfcp:
    - address: 172.22.0.20