logger:
  level: info

global:
  max:
    ue: 1024

upf:
  pfcp:
    server:
      - address: 172.22.0.20
    client: []

  gtpu:
    server:
      - address: 172.22.0.20

  session:
    - subnet: 10.45.0.0/16
      dnn: internet
    - subnet: 10.46.0.0/16
      dnn: ims

  metrics:
    server:
      - address: 172.22.0.20
        port: 9090

smf:
  pfcp:
    server:
      - address: 172.22.0.13